import type { Config } from 'tailwindcss';
import animate from 'tailwindcss-animate';
import scrollbar from 'tailwind-scrollbar';

export default {
    darkMode: ['class'],
    content: [
        './index.html',
        './src/**/*.{ts,tsx}',
        '../../packages/radix-ui/**/*.{js,ts,jsx,tsx}',
    ],
    prefix: '',
    theme: {
        container: {
            center: true,
            padding: '2rem',
            screens: {
                '2xl': '1400px',
            },
        },
        extend: {
            colors: {
                border: 'hsl(var(--border))',
                input: 'hsl(var(--input))',
                ring: 'hsl(var(--ring))',
                background: 'hsl(var(--background))',
                foreground: 'hsl(var(--foreground))',
                primary: {
                    DEFAULT: 'hsl(var(--primary))',
                    foreground: 'hsl(var(--primary-foreground))',
                },
                secondary: {
                    DEFAULT: 'hsl(var(--secondary))',
                    foreground: 'hsl(var(--secondary-foreground))',
                },
                destructive: {
                    DEFAULT: 'hsl(var(--destructive))',
                    foreground: 'hsl(var(--destructive-foreground))',
                },
                muted: {
                    DEFAULT: 'hsl(var(--muted))',
                    foreground: 'hsl(var(--muted-foreground))',
                },
                accent: {
                    DEFAULT: 'hsl(var(--accent))',
                    foreground: 'hsl(var(--accent-foreground))',
                },
                popover: {
                    DEFAULT: 'hsl(var(--popover))',
                    foreground: 'hsl(var(--popover-foreground))',
                },
                card: {
                    DEFAULT: 'hsl(var(--card))',
                    foreground: 'hsl(var(--card-foreground))',
                },
                sidebar: {
                    DEFAULT: 'hsl(var(--sidebar-background))',
                    foreground: 'hsl(var(--sidebar-foreground))',
                    primary: 'hsl(var(--sidebar-primary))',
                    'primary-foreground':
                        'hsl(var(--sidebar-primary-foreground))',
                    accent: 'hsl(var(--sidebar-accent))',
                    'accent-foreground':
                        'hsl(var(--sidebar-accent-foreground))',
                    border: 'hsl(var(--sidebar-border))',
                    ring: 'hsl(var(--sidebar-ring))',
                },
                // Primes와 동일한 커스텀 컬러 시스템
                'Colors-Base-white': '#FFFFFFFF',
                'Colors-Base-black': '#000000FF',
                'Colors-Base-transparent': '#FFFFFF00',
                'Colors-Gray-(light-mode)-25': '#FDFDFDFF',
                'Colors-Gray-(light-mode)-50': '#FAFAFAFF',
                'Colors-Gray-(light-mode)-100': '#F5F5F5FF',
                'Colors-Gray-(light-mode)-200': '#E9EAEBFF',
                'Colors-Gray-(light-mode)-300': '#D5D7DAFF',
                'Colors-Gray-(light-mode)-400': '#A4A7AEFF',
                'Colors-Gray-(light-mode)-500': '#717680FF',
                'Colors-Gray-(light-mode)-600': '#535862FF',
                'Colors-Gray-(light-mode)-700': '#414651FF',
                'Colors-Gray-(light-mode)-800': '#252B37FF',
                'Colors-Gray-(light-mode)-900': '#181D27FF',
                'Colors-Gray-(light-mode)-950': '#0A0D12FF',
                'Colors-Brand-25': '#F5F5FAFF',
                'Colors-Brand-50': '#F1F0F8FF',
                'Colors-Brand-100': '#E3E0F2FF',
                'Colors-Brand-200': '#CBC5E7FF',
                'Colors-Brand-300': '#B1A7DBFF',
                'Colors-Brand-400': '#9A8DD0FF',
                'Colors-Brand-500': '#8270C2FF',
                'Colors-Brand-600': '#6A53B1FF',
                'Colors-Brand-700': '#4F3B8AFF',
                'Colors-Brand-800': '#372863FF',
                'Colors-Brand-900': '#1E153BFF',
                'Colors-Brand-950': '#130C28FF',
                'Colors-Error-25': '#FFFBFAFF',
                'Colors-Error-50': '#FEF3F2FF',
                'Colors-Error-100': '#FEE4E2FF',
                'Colors-Error-200': '#FECDCAFF',
                'Colors-Error-300': '#FDA29BFF',
                'Colors-Error-400': '#F97066FF',
                'Colors-Error-500': '#F04438FF',
                'Colors-Error-600': '#D92D20FF',
                'Colors-Error-700': '#B42318FF',
                'Colors-Error-800': '#912018FF',
                'Colors-Error-900': '#7A271AFF',
                'Colors-Error-950': '#55160CFF',
                'Colors-Warning-25': '#FFFCF5FF',
                'Colors-Warning-50': '#FFFAEBFF',
                'Colors-Warning-100': '#FEF0C7FF',
                'Colors-Warning-200': '#FEDF89FF',
                'Colors-Warning-300': '#FEC84BFF',
                'Colors-Warning-400': '#FDB022FF',
                'Colors-Warning-500': '#F79009FF',
                'Colors-Warning-600': '#DC6803FF',
                'Colors-Warning-700': '#B54708FF',
                'Colors-Warning-800': '#93370DFF',
                'Colors-Warning-900': '#7A2E0EFF',
                'Colors-Warning-950': '#4E1D09FF',
                'Colors-Success-25': '#F6FEF9FF',
                'Colors-Success-50': '#ECFDF3FF',
                'Colors-Success-100': '#DCFAE6FF',
                'Colors-Success-200': '#ABEFC6FF',
                'Colors-Success-300': '#75E0A7FF',
                'Colors-Success-400': '#47CD89FF',
                'Colors-Success-500': '#17B26AFF',
                'Colors-Success-600': '#079455FF',
                'Colors-Success-700': '#067647FF',
                'Colors-Success-800': '#085D3AFF',
                'Colors-Success-900': '#074D31FF',
                'Colors-Success-950': '#053321FF',
            },
            borderRadius: {
                lg: 'var(--radius)',
                md: 'calc(var(--radius) - 2px)',
                sm: 'calc(var(--radius) - 4px)',
            },
            keyframes: {
                'accordion-down': {
                    from: {
                        height: '0',
                    },
                    to: {
                        height: 'var(--radix-accordion-content-height)',
                    },
                },
                'accordion-up': {
                    from: {
                        height: 'var(--radix-accordion-content-height)',
                    },
                    to: {
                        height: '0',
                    },
                },
                fadeIn: {
                    from: {
                        opacity: '0',
                    },
                    to: {
                        opacity: '1',
                    },
                },
            },
            animation: {
                'accordion-down': 'accordion-down 0.3s ease-in-out',
                'accordion-up': 'accordion-up 0.3s ease-in-out',
                'fade-in': 'fadeIn 0.3s ease-in-out forwards',
            },
            spacing: {
                'Spacing-0-(0px)': '0px',
                'Spacing-0․5-(2px)': '2px',
                'Spacing-1-(4px)': '4px',
                'Spacing-1․5-(6px)': '6px',
                'Spacing-2-(8px)': '8px',
                'Spacing-3-(12px)': '12px',
                'Spacing-4-(16px)': '16px',
                'Spacing-5-(20px)': '20px',
                'Spacing-6-(24px)': '24px',
                'Spacing-8-(32px)': '32px',
                'Spacing-10-(40px)': '40px',
                'Spacing-12-(48px)': '48px',
                'Spacing-16-(64px)': '64px',
                'Spacing-20-(80px)': '80px',
                'Spacing-24-(96px)': '96px',
                'Spacing-32-(128px)': '128px',
                'Spacing-40-(160px)': '160px',
                'Spacing-48-(192px)': '192px',
                'Spacing-56-(224px)': '224px',
                'Spacing-64-(256px)': '256px',
                'Spacing-80-(320px)': '320px',
                'Spacing-96-(384px)': '384px',
                'Spacing-120-(480px)': '480px',
                'Spacing-140-(560px)': '560px',
                'Spacing-160-(640px)': '640px',
                'Spacing-180-(720px)': '720px',
                'Spacing-192-(768px)': '768px',
                'Spacing-256-(1,024px)': '1024px',
                'Spacing-320-(1,280px)': '1280px',
                'Spacing-360-(1,440px)': '1440px',
                'Spacing-400-(1,600px)': '1600px',
                'Spacing-480-(1,920px)': '1920px',
            },
        },
    },
    plugins: [scrollbar, animate],
} satisfies Config;