import { Item } from '@primes/types/item';

// BOM 관리용 더미 데이터
export const bomData: Item[] = [
	{
		id: 1,
		tenantId: 1,
		isDelete: false,
		isUse: true,
		itemNo: 2001,
		itemNumber: 'BOM-001',
		itemName: '스마트폰 완제품 BOM',
		itemSpec: '스마트폰 조립',
		itemModel: 'v1.0',
		itemType1: '완제품',
		itemType2: 'BOM',
		itemType3: '조립품',
		itemUnit: 'EA',
		lotSize: '100',
		optimalInventoryQty: 8,
		safetyInventoryQty: 3,
		createdBy: 'admin',
		createdAt: '2024-01-15T09:00:00Z',
		updatedBy: 'admin',
		updatedAt: '2024-01-15T09:00:00Z',
		accountYear: 2024,
		useState: true,
		deleteState: false,
	},
	{
		id: 2,
		tenantId: 1,
		isDelete: false,
		isUse: true,
		itemNo: 2002,
		itemNumber: 'BOM-002',
		itemName: '무선 이어폰 BOM',
		itemSpec: '이어폰 조립',
		itemModel: 'v2.1',
		itemType1: '완제품',
		itemType2: 'BOM',
		itemType3: '조립품',
		itemUnit: 'SET',
		lotSize: '50',
		optimalInventoryQty: 12,
		safetyInventoryQty: 4,
		createdBy: 'manager',
		createdAt: '2024-01-16T10:30:00Z',
		updatedBy: 'manager',
		updatedAt: '2024-01-16T10:30:00Z',
		accountYear: 2024,
		useState: true,
		deleteState: false,
	},
	{
		id: 3,
		tenantId: 1,
		isDelete: false,
		isUse: true,
		itemNo: 2003,
		itemNumber: 'BOM-003',
		itemName: 'USB 케이블 BOM',
		itemSpec: '케이블 조립',
		itemModel: 'v1.5',
		itemType1: '반제품',
		itemType2: 'BOM',
		itemType3: '조립품',
		itemUnit: 'EA',
		lotSize: '200',
		optimalInventoryQty: 5,
		safetyInventoryQty: 2,
		createdBy: 'admin',
		createdAt: '2024-01-17T14:15:00Z',
		updatedBy: 'admin',
		updatedAt: '2024-01-17T14:15:00Z',
		accountYear: 2024,
		useState: true,
		deleteState: false,
	},
	{
		id: 4,
		tenantId: 1,
		isDelete: false,
		isUse: true,
		itemNo: 2004,
		itemNumber: 'BOM-004',
		itemName: '블루투스 스피커 BOM',
		itemSpec: '스피커 조립',
		itemModel: 'v2.0',
		itemType1: '완제품',
		itemType2: 'BOM',
		itemType3: '조립품',
		itemUnit: 'EA',
		lotSize: '30',
		optimalInventoryQty: 15,
		safetyInventoryQty: 5,
		createdBy: 'manager',
		createdAt: '2024-01-18T11:45:00Z',
		updatedBy: 'manager',
		updatedAt: '2024-01-18T11:45:00Z',
		accountYear: 2024,
		useState: true,
		deleteState: false,
	},
	{
		id: 5,
		tenantId: 1,
		isDelete: false,
		isUse: true,
		itemNo: 2005,
		itemNumber: 'BOM-005',
		itemName: '충전패드 BOM',
		itemSpec: '충전기 조립',
		itemModel: 'v1.8',
		itemType1: '완제품',
		itemType2: 'BOM',
		itemType3: '조립품',
		itemUnit: 'EA',
		lotSize: '80',
		optimalInventoryQty: 10,
		safetyInventoryQty: 3,
		createdBy: 'admin',
		createdAt: '2024-01-19T16:20:00Z',
		updatedBy: 'admin',
		updatedAt: '2024-01-19T16:20:00Z',
		accountYear: 2024,
		useState: true,
		deleteState: false,
	},
];
