import { Item } from '@primes/types/item';

// 공정 라우팅용 더미 데이터
export const processRoutingData: Item[] = [
	{
		id: 1,
		tenantId: 1,
		isDelete: false,
		isUse: true,
		itemNo: 3001,
		itemNumber: 'RT-001',
		itemName: '스마트폰 조립 라우팅',
		itemSpec: '스마트폰 생산 공정',
		itemModel: 'v1.0',
		itemType1: '조립',
		itemType2: '라우팅',
		itemType3: '생산',
		itemUnit: 'EA',
		lotSize: '100',
		optimalInventoryQty: 8,
		safetyInventoryQty: 120,
		createdBy: 'admin',
		createdAt: '2024-01-15T09:00:00Z',
		updatedBy: 'admin',
		updatedAt: '2024-01-15T09:00:00Z',
		accountYear: 2024,
		useState: true,
		deleteState: false,
	},
	{
		id: 2,
		tenantId: 1,
		isDelete: false,
		isUse: true,
		itemNo: 3002,
		itemNumber: 'RT-002',
		itemName: '이어폰 조립 라우팅',
		itemSpec: '이어폰 생산 공정',
		itemModel: 'v2.1',
		itemType1: '조립',
		itemType2: '라우팅',
		itemType3: '생산',
		itemUnit: 'SET',
		lotSize: '50',
		optimalInventoryQty: 6,
		safetyInventoryQty: 90,
		createdBy: 'manager',
		createdAt: '2024-01-16T10:30:00Z',
		updatedBy: 'manager',
		updatedAt: '2024-01-16T10:30:00Z',
		accountYear: 2024,
		useState: true,
		deleteState: false,
	},
	{
		id: 3,
		tenantId: 1,
		isDelete: false,
		isUse: true,
		itemNo: 3003,
		itemNumber: 'RT-003',
		itemName: '케이블 조립 라우팅',
		itemSpec: '케이블 생산 공정',
		itemModel: 'v1.5',
		itemType1: '조립',
		itemType2: '라우팅',
		itemType3: '생산',
		itemUnit: 'EA',
		lotSize: '200',
		optimalInventoryQty: 4,
		safetyInventoryQty: 60,
		createdBy: 'admin',
		createdAt: '2024-01-17T14:15:00Z',
		updatedBy: 'admin',
		updatedAt: '2024-01-17T14:15:00Z',
		accountYear: 2024,
		useState: true,
		deleteState: false,
	},
	{
		id: 4,
		tenantId: 1,
		isDelete: false,
		isUse: true,
		itemNo: 3004,
		itemNumber: 'RT-004',
		itemName: '스피커 조립 라우팅',
		itemSpec: '스피커 생산 공정',
		itemModel: 'v2.0',
		itemType1: '조립',
		itemType2: '라우팅',
		itemType3: '생산',
		itemUnit: 'EA',
		lotSize: '30',
		optimalInventoryQty: 10,
		safetyInventoryQty: 150,
		createdBy: 'manager',
		createdAt: '2024-01-18T11:45:00Z',
		updatedBy: 'manager',
		updatedAt: '2024-01-18T11:45:00Z',
		accountYear: 2024,
		useState: true,
		deleteState: false,
	},
	{
		id: 5,
		tenantId: 1,
		isDelete: false,
		isUse: true,
		itemNo: 3005,
		itemNumber: 'RT-005',
		itemName: '충전기 조립 라우팅',
		itemSpec: '충전기 생산 공정',
		itemModel: 'v1.8',
		itemType1: '조립',
		itemType2: '라우팅',
		itemType3: '생산',
		itemUnit: 'EA',
		lotSize: '80',
		optimalInventoryQty: 7,
		safetyInventoryQty: 105,
		createdBy: 'admin',
		createdAt: '2024-01-19T16:20:00Z',
		updatedBy: 'admin',
		updatedAt: '2024-01-19T16:20:00Z',
		accountYear: 2024,
		useState: true,
		deleteState: false,
	},
];
