import { Machine } from '../machine-master/MachineMasterPage';

export const machineMasterData: Machine[] = [
	{
		id: 1,
		machineCode: 'MC-1001',
		machineName: 'CNC Lathe #1',
		workCenterName: 'WC-Machining',
		calendarName: 'Default Shift A',
		capacityPerHour: 120,
		efficiencyPct: 88,
		utilizationPct: 76,
		status: 'Running',
		lastMaintenanceAt: '2025-07-15',
		nextMaintenanceAt: '2025-09-15',
	},
	{
		id: 2,
		machineCode: 'MC-2001',
		machineName: 'Injection Molder #2',
		workCenterName: 'WC-Molding',
		calendarName: '3-Shift',
		capacityPerHour: 80,
		efficiencyPct: 92,
		utilizationPct: 65,
		status: 'Idle',
		lastMaintenanceAt: '2025-06-30',
		nextMaintenanceAt: '2025-08-30',
	},
	{
		id: 3,
		machineCode: 'MC-3005',
		machineName: 'Press #5',
		workCenterName: 'WC-Press',
		calendarName: 'Weekend OT',
		capacityPerHour: 200,
		efficiencyPct: 81,
		utilizationPct: 83,
		status: 'Maintenance',
		lastMaintenanceAt: '2025-08-10',
		nextMaintenanceAt: '2025-10-10',
	},
	{
		id: 4,
		machineCode: 'MC-3007',
		machineName: 'Press #7',
		workCenterName: 'WC-Press',
		calendarName: 'Weekend OT',
		capacityPerHour: 200,
		efficiencyPct: 81,
		utilizationPct: 83,
		status: 'Running',
		lastMaintenanceAt: '2025-08-10',
		nextMaintenanceAt: '2025-10-10',
	},
	{
		id: 5,
		machineCode: 'MC-3009',
		machineName: 'Press #2',
		workCenterName: 'WC-Press',
		calendarName: 'Weekend OT',
		capacityPerHour: 200,
		efficiencyPct: 81,
		utilizationPct: 83,
		status: 'Running',
		lastMaintenanceAt: '2025-08-10',
		nextMaintenanceAt: '2025-10-10',
	},
];
