import { SupplyData } from './MrpSupplyListPage';

// Dummy supply data
export const supplyDummyData: SupplyData[] = [
	{
		id: 1,
		supplierName: 'ABC Materials Co.',
		supplierCode: 'SUP001',
		materialName: 'Steel Plate A4',
		materialCode: 'MAT001',
		currentStock: 150,
		reorderPoint: 100,
		leadTime: 7,
		unitPrice: 25.5,
		lastOrderDate: '2024-01-15',
		nextDeliveryDate: '2024-01-22',
		status: 'In Stock',
		category: 'Raw Materials',
	},
	{
		id: 2,
		supplierName: 'XYZ Electronics',
		supplierCode: 'SUP002',
		materialName: 'Circuit Board PCB-100',
		materialCode: 'MAT002',
		currentStock: 45,
		reorderPoint: 50,
		leadTime: 14,
		unitPrice: 85.0,
		lastOrderDate: '2024-01-10',
		nextDeliveryDate: '2024-01-25',
		status: 'Low Stock',
		category: 'Electronics',
	},
	{
		id: 3,
		supplierName: 'Global Plastics Ltd',
		supplierCode: 'SUP003',
		materialName: 'Plastic Housing PH-200',
		materialCode: 'MAT003',
		currentStock: 0,
		reorderPoint: 25,
		leadTime: 10,
		unitPrice: 12.75,
		lastOrderDate: '2024-01-05',
		nextDeliveryDate: '2024-01-20',
		status: 'Out of Stock',
		category: 'Components',
	},
	{
		id: 4,
		supplierName: 'Premium Fasteners Inc',
		supplierCode: 'SUP004',
		materialName: 'Bolt Set M8x20',
		materialCode: 'MAT004',
		currentStock: 500,
		reorderPoint: 200,
		leadTime: 3,
		unitPrice: 0.85,
		lastOrderDate: '2024-01-18',
		nextDeliveryDate: '2024-01-21',
		status: 'On Order',
		category: 'Hardware',
	},
	{
		id: 5,
		supplierName: 'Tech Components Corp',
		supplierCode: 'SUP005',
		materialName: 'Sensor Module SM-500',
		materialCode: 'MAT005',
		currentStock: 75,
		reorderPoint: 30,
		leadTime: 21,
		unitPrice: 145.0,
		lastOrderDate: '2024-01-12',
		nextDeliveryDate: '2024-02-02',
		status: 'In Stock',
		category: 'Electronics',
	},
];
