import { FormField } from '@primes/components/form/DynamicFormComponent';
import { useTranslation } from '@repo/i18n';

// WorkingMaster 목록 컬럼 정의
export const workingMasterColumns = () => {
    const { t } = useTranslation('dataTable');

    return [
		{
			name: 'commandId',
			label: t('columns.commandId'),
			type: 'hidden',
			required: false,
		},
		{
			name: 'commandNo',
			label: t('columns.commandNo'),
			type: 'text',
			placeholder: t('columns.commandNo'),
			disabled: true,
		},
		{
			name: 'workCode',
			label: t('columns.workCode'),
			type: 'text',
			placeholder: t('placeholders.workCodeAutoGenerated'),
			disabled: true,
		},
		{
			name: 'workBy',
			label: t('columns.workBy'),
			type: 'userSelect',
			placeholder: t('columns.workBy'),
			required: false,
		},
		{
			name: 'workDate',
			label: t('columns.workDate'),
			type: 'date',
			required: false,
		},
		{
			name: 'standardTime',
			label: t('columns.standardTime'),
			type: 'text',
			pattern: /^\d+$/,
			placeholder: t('columns.standardTime'),
			required: false,
		},
		{
			name: 'shift',
			label: t('columns.shift'),
			type: 'codeSelect',
			placeholder: t('columns.shift'),
            fieldKey: 'PDC-005',
			required: false,
		},
		{
			name: 'startTime',
			label: t('columns.startTime'),
			type: 'datetime-local',
			required: false,
		},
		{
			name: 'endTime',
			label: t('columns.endTime'),
			type: 'datetime-local',
			required: false,
		},
    ]
};